#! /usr/bin/env bash

set -euo pipefail

# -- global variables ---------------------------------------------------------

FMA_OS_LINUX="linux"
FMA_OS_MACOS="macos"
FMA_OS_UNDEF="undef"

FMA_OS="${FMA_OS_UNDEF}"
FMA_OS=""

# -- os detection -------------------------------------------------------------

current_os="$(uname)"

# checks if this is supported OS
case "${current_os}" in
    Linux)
        FMA_OS="${FMA_OS_LINUX}"
    ;;

    Darwin)
        FMA_OS="${FMA_OS_MACOS}"
    ;;

    *)
        >&2 echo
        >&2 echo "${current_os} is not supported operating system."
        exit 1
esac

# -- absolute dirpath ---------------------------------------------------------

ABSOLUTE_DIRPATH="$( cd "$( dirname "$( [[ -L "${BASH_SOURCE[0]}" ]] && readlink "${BASH_SOURCE[0]}" || echo "${BASH_SOURCE[0]}" )" )" && pwd )" || { \
    >&2 echo
    >&2 echo "Cannot determine real path of the script."
    exit 1
}

# -- load libraries -----------------------------------------------------------

# shellcheck source=vendor/fidian/ansi/ansi
. "${ABSOLUTE_DIRPATH}/vendor/fidian/ansi/ansi"

# shellcheck source=libs/utils
. "${ABSOLUTE_DIRPATH}/libs/utils"

# shellcheck source=libs/network
. "${ABSOLUTE_DIRPATH}/libs/network"

case "${FMA_OS}" in
    "${FMA_OS_LINUX}")
        # shellcheck source=libs/network.linux
        . "${ABSOLUTE_DIRPATH}/libs/network.linux"
    ;;

    "${FMA_OS_MACOS}")
        # shellcheck source=libs/network.macos
        . "${ABSOLUTE_DIRPATH}/libs/network.macos"
    ;;
esac

# -- initial setup ------------------------------------------------------------

if [[ ${#} -eq 0 ]] && [[ -z "${FMA_CONFIG_FILEPATH+_}" ]]; then
    fma::utils::usage
    fma::utils::terminate "Environment variable FMA_CONFIG_FILEPATH is not set and filepath was not passed via an argument."
elif [[ ${#} -gt 0 ]]; then
    fma::utils::parse_input "${@}"
fi

if [[ ! -e "${FMA_CONFIG_FILEPATH}" ]]; then
    fma::utils::terminate "Configuration file [${FMA_CONFIG_FILEPATH}] doesn't exist."
elif [[ ! -r "${FMA_CONFIG_FILEPATH}" ]]; then
    fma::utils::terminate "Can't read configuration file [${FMA_CONFIG_FILEPATH}]."
fi

# shellcheck source=fma.example.cfg
. "${FMA_CONFIG_FILEPATH}"

# -- main program -------------------------------------------------------------

echo
echo "Pre-flight checks"

echo "› checking interface ${affected_interface}"
fma::network::interface_exists "${affected_interface}"

echo "› checking current mac address of interface ${affected_interface}"
fma::network::check_mac_address_before "${affected_interface}" "${fake_mac_address}"

echo
echo "Faking mac address"

echo "› invoke sudo"
fma::utils::invoke_sudo

echo "› fake mac address ${fake_mac_address}"
fma::network::fake_mac_address "${affected_interface}" "${fake_mac_address}"

echo "› restarting interface ${affected_interface}"
fma::network::restart_affected_interface "${affected_interface}"

echo "› verifying current mac address"
fma::network::check_mac_address_after "${affected_interface}" "${fake_mac_address}"
