#! /usr/bin/env bash

function fma::flow::preflight_checks() {
    echo
    echo "Pre-flight checks"

    echo "› checking interface ${FMA_AFFECTED_INTERFACE}"
    fma::network::interface_exists "${FMA_AFFECTED_INTERFACE}"

    echo "› checking current mac address of interface ${FMA_AFFECTED_INTERFACE}"
    fma::network::check_mac_address_before "${FMA_AFFECTED_INTERFACE}" "${FMA_FAKE_MAC_ADDRESS}"

    # OS specific pre-flight checks
    fma::flow::"$FMA_OS"::preflight_checks
}

function fma::flow::fake_mac_address() {
    echo
    echo "Faking mac address"

    echo "› invoke sudo"
    fma::utils::invoke_sudo

    # OS specific faking
    fma::flow::"$FMA_OS"::fake_mac_address

    echo "› verifying current mac address"
    fma::network::check_mac_address_after "${FMA_AFFECTED_INTERFACE}" "${FMA_FAKE_MAC_ADDRESS}"
}
