#! /usr/bin/env bash

function fma::flow::preflight_checks() {
    echo
    echo "Pre-flight checks"

    echo "› checking configuration"
    fma::flow::check_configuration

    echo "› checking interface ${affected_interface}"
    fma::network::interface_exists "${affected_interface}"

    echo "› checking current mac address of interface ${affected_interface}"
    fma::network::check_mac_address_before "${affected_interface}" "${fake_mac_address}"

    # OS specific pre-flight checks
    fma::flow::"$FMA_OS"::preflight_checks
}

function fma::flow::fake_mac_address() {
    echo
    echo "Faking mac address"

    echo "› invoke sudo"
    fma::utils::invoke_sudo

    # OS specific faking
    fma::flow::"$FMA_OS"::fake_mac_address

    echo "› verifying current mac address"
    fma::network::check_mac_address_after "${affected_interface}" "${fake_mac_address}"
}

function fma::flow::check_configuration() {
    if [[ -z "${affected_interface+x}" ]]; then
        fma::utils::terminate "Configuration parametr [affected_interface] is not set."
    fi

    if [[ -z "${fake_mac_address+x}" ]]; then
        fma::utils::terminate "Configuration parametr [fake_mac_address] is not set."
    fi

    fma::utils::success "Configuration is set."
}
