#! /usr/bin/env bash

function fma::utils::terminate() {
    local exit_code="1"
    local message=""

    if [[ ${#} -eq 1 ]]; then
        message="${1}"
    elif [[ ${#} -eq 2 ]]; then
        exit_code="${1}"
        message="${2}"
    fi

    if [[ ${#} -ne 0 ]]; then
        >&2 echo
        >&2 ansi --bold --red "The program has been terminated due to a critical error:"
        >&2 echo
        >&2 echo "${message}"
    fi

    exit "${exit_code}"
}

function fma::utils::terminate_with_code() {
    exit "${1}"
}

function fma::utils::success() {
    echo "  [  $(ansi --green "OK")  ] ${1}"
}

function fma::utils::fail() {
    echo "  [ $(ansi --red "FAIL") ] ${1}"
}

function fma::utils::info() {
    echo "  [ $(ansi --yellow "INFO") ] ${1}"
}

function fma::utils::skipped() {
    echo "  [ $(ansi --blue "SKIP") ] ${1}"
}

function fma::utils::report_status() {
    local rc_of_last_command="${?}" # ! has to be on the 1st line

    local message_success="${1}"
    local message_failure="${1}"

    if [[ ${#} -eq 2 ]]; then
        message_failure="${2}"
    fi

    if [[ ${rc_of_last_command} -eq 0 ]]; then
        fma::utils::success "${message_success}"
    else
        fma::utils::fail "${message_failure}"
    fi
}

function fma::utils::invoke_sudo() {
    if sudo echo &> /dev/null; then
        fma::utils::success "sudo authentication successfull"
    else
        fma::utils::fail "sudo authentication failed"
        fma::utils::terminate
    fi
}

function fma::utils::is_installed() {
    command which "${1}" &> /dev/null && return 0

    return 1
}

function fma::utils::load_configuration() {
    # shellcheck source=fma.example.cfg
    . "${FMA_CONFIG_FILEPATH}"

    if [[ -z "${FMA_AFFECTED_INTERFACE+_}" ]]; then
        FMA_AFFECTED_INTERFACE="${affected_interface}"
    fi

    if [[ -z "${FMA_FAKE_MAC_ADDRESS+_}" ]]; then
        FMA_FAKE_MAC_ADDRESS="${fake_mac_address}"
    fi
}

function fma::utils::usage() {
    # shellcheck disable=SC2155
    local fmt_bold="$(ansi --bold --no-restore)"
    # shellcheck disable=SC2155
    local fmt_underline="$(ansi --underline --no-restore)"
    # shellcheck disable=SC2155
    local fmt_reset="$(ansi --reset-attrib)"

    >&2 echo
    >&2 echo "Usage: $0 [-${_FMA_CONFIG_FILEPATH_OPTION} <config-filepath>] [-${_FMA_AFFECTED_INTERFACE_OPTION} <affected-interface>] [-${_FMA_FAKE_MAC_ADDRESS_OPTION} <fake_mac_address>] [-h]"
    >&2 echo
    >&2 echo "    ${fmt_bold}-${_FMA_CONFIG_FILEPATH_OPTION} <filepath>${fmt_reset}"
    >&2 echo "        Filepath to config file."
    >&2 echo
    >&2 echo "    ${fmt_bold}-${_FMA_AFFECTED_INTERFACE_OPTION} <affected-interface>${fmt_reset}"
    >&2 echo "        Interface to affect."
    >&2 echo
    >&2 echo "    ${fmt_bold}-${_FMA_FAKE_MAC_ADDRESS_OPTION} <fake_mac_address>${fmt_reset}"
    >&2 echo "        MAC address to spoof."
    >&2 echo
    >&2 echo "    ${fmt_bold}-${_FMA_HELP_OPTION}${fmt_reset}"
    >&2 echo "        Prints this help."
    >&2 echo
    >&2 echo "${fmt_underline}Environment variables${fmt_reset}"
    >&2 echo "    ${fmt_bold}FMA_CONFIG_FILEPATH${fmt_reset} - filepath to config file"
}
